# -*- coding: utf-8 -*-
"""data_extration_using_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRMz78RGkJqn-V4rLmcXPNKd0nbC42b-
"""

#store the url
#get request using requests
#chek the status code and status
#display as text, content
#convert into json
#use dumps
#display the keys
#display values which keys are holding
#pass the specfic end-point and merge it the base_url, refer documentation
#pass the specfic date end-point and merge it the base_url, refer documentation
#list down the currencies
#raise_for_status()
#.raw
#.iter_content
#history
#headers - We can view the server’s response headers using a Python dictionary:
#requests.get('https://github.com/', timeout=0.001)

import requests
import json
import pandas as pd

url="https://api.frankfurter.dev/v1/latest"
old_url="https://api.frankfurter.dev/v1/"
print(url)
print(old_url)

res=requests.get(url)
print(res)
print(res.ok)
print(res.status_code)
print(type(res))

res_txt=res.text
print(res_txt)
print(type(res_txt))
res_con=res.content # access the response body as bytes, for non-text requests
print(res_con)
print(type(res_con))

data=res.json()
print(type(data))
print(data.keys())
print(data['amount']) # accessing the dict value's by their key's
print(data['date'])
print(data['base'])
print(data['rates'])
print(data['rates']['USD'])
print(data['rates']['INR'])
print(data)

js_data=json.dumps(data, indent=2)  # converts into a JSON formatted text (string)
print(type(data))
print(type(js_data))

# Change the base currency using the base parameter. The default is EUR.
usd=url+ "?base=USD"
print(usd)

# Limit the response to specific target currencies.
symbols=url + "?symbols=CHF,GBP,INR,USD,AUD"
print(symbols)
# written simple money conversion EUR to INR
sym=requests.get(symbols)
print(sym.json().keys())
data=sym.json()
amt_EUR=data['amount']
amt_INR=data['rates']['INR']
print("One Euro value: ",amt_EUR)
print("One Euro in INR: ", data['rates']['INR'])
x= 4#int(input("Enter the Euro Value: "))
y=int(x*amt_INR)
print("{0} Euro in INR: {1}". format(x,y))

# Historical Rates
# Retrieve rates for a specific date.
print(old_url)
date=old_url+"2024-02-03"
print(date)
data_date=requests.get(date)
print(data_date.json())

# Change the base currency and filter target currencies
rates_date=date+"?base=USD&symbols=EUR"
print(rates_date)
date_rates_date=requests.get(rates_date)
print(date_rates_date.json())

# Time Series Data
# Fetch rates over a period.
over_dates=old_url+"2026-01-01..2026-01-03"
print(over_dates)
data_dates=requests.get(over_dates)
print(data_dates.json())

# Fetch rates up to the present.
# path=['2024-01-01..']
# upto_date=old_url+path[0]
# print(upto_date)
# data_upto_date=requests.get(upto_date)
# print(data_upto_date.json())
# print(repr(upto_date))

# Filter currencies to reduce response size and improve performance.
fil_url=old_url+"2026-01-01..?symbols=INR"
print(fil_url)
data_fil_url=requests.get(fil_url)
print(data_fil_url.json())

# Available currencies
# Get supported currency symbols and their full names.
cur=old_url+"currencies"
print(cur)
data_cur=requests.get(cur, stream=True)
print(data_cur.json())

js_data_cur=data_cur.json()
print(js_data_cur.keys())
print(type(js_data_cur))
# print(pd.Series(js_data_cur['AUD']))
# print(pd.Series(js_data_cur['INR']))

# some additional works
raw_data = data_cur.raw.read()
print(raw_data)
print(data_cur.url)
print(data_cur.status_code)
print(data_cur.history)
print(type(data_cur.iter_content))

# headers
head=dict(data_cur.headers)
print(head)
print(type(head))

# Exception handling
try:
    # session = requests.Session()
    # response = session.get(cur, timeout=0.005)
    response = requests.get(cur, timeout=0.018)
    response.raise_for_status()
    data = response.json()
except requests.exceptions.Timeout as e:
  print("Timeout!!!", e)
except requests.exceptions.HTTPError as e:
    print("HTTP error occurred:", e)
except requests.exceptions.RequestException as e:
    print("Request failed!:", e)