# -*- coding: utf-8 -*-
"""official_joke_api.ipyn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrDo3YmLgIqM10xUb3ajK4TrzTGiZ4KT

**📋 Project Summary :**
**This project explores the automated collection and structured analysis of comedic data. I performed a full "mini-ETL" (Extract, Transform, Load) process, moving data from a live API into a cleaned, analysis-ready format.**
"""

# Passed comman path to urk variable (url)

# Grab a random joke (ran_jokes)
# https://official-joke-api.appspot.com/random_joke
# https://official-joke-api.appspot.com/jokes/random

# Get joke types (jok_types)
# https://official-joke-api.appspot.com/types

# Grab jokes by types [programming, dad, general, knock-knock] (type_joke)
# https://official-joke-api.appspot.com/jokes/programming/random
# https://official-joke-api.appspot.com/jokes/programming/ten

# Grab ten random jokes (ten_random)
# https://official-joke-api.appspot.com/random_ten
# https://official-joke-api.appspot.com/jokes/ten

# Grab any number of random jokes (num_jok)
# https://official-joke-api.appspot.com/jokes/random/5
# https://official-joke-api.appspot.com/jokes/random/25
# https://official-joke-api.appspot.com/jokes/random/250

import requests
import json
import pandas as pd
import numpy as np

pr=input("Enter the type one (programming,dad,genral,knock-knock): ")
pr=pr.lower()

url="https://official-joke-api.appspot.com/jokes/"
ran_jokes=url+"random"
jok_types="https://official-joke-api.appspot.com/types"
type_joke=url+ pr + "/random"
ten_random=url+"ten"
num_jok=url+"random/451"
print(ran_jokes)
print(jok_types)
print(type_joke)
print(ten_random)
print(num_jok)

all_url=[ran_jokes,jok_types,type_joke,ten_random,num_jok]
one= requests.get(ran_jokes)
# Sending the HTTP requets via session()
with requests.Session() as session:
  for i in range(len(all_url)):
    all_url[i]=session.get(all_url[i])
    print(all_url[i])

res_num_jok= requests.get(num_jok)
print(res_num_jok)
print(res_num_jok.json())
print(len(res_num_jok.json()))
print(json.dumps(res_num_jok.json(), indent=4))

raw_data=res_num_jok.json()
print(raw_data)
data=json.dumps(res_num_jok.json(), indent=4)

frame=pd.DataFrame(raw_data)
frame=frame.set_index('id')
frame.head()
sorted_id=frame.sort_values(by='id')
sorted_type=frame.sort_values(by='type')
print(frame.shape)
sorted
sorted_type
print(len(frame['type']))
sorted_id

c=sorted_id.to_csv("Jokes file id_sorted.csv")
print(type(c))

na=sorted_id.isna()
#print(type(unique))
print(na)